# Generated by Django 6.0.3 on 2026-05-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, help_text='Descripcion de la categoria del inventario', null=True)),
                ('fecha_creacion_categoria', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=200)),
                ('marca_item', models.CharField(max_length=100)),
                ('descripcion_item', models.TextField(blank=True, help_text='Descripcion del item del inventario', null=True)),
                ('ubicacion_item', models.CharField(help_text='Ej: Salon 203 - laboratorio', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateField()),
                ('valor_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_item', models.CharField(choices=[('1', 'DISPONIBLE'), ('2', 'PRESTADO'), ('3', 'MANTENIMIENTO'), ('4', 'DAÑADO')], default='1', max_length=14)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', related_query_name='categoria', to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado_prestamo', models.CharField(choices=[('1', 'PRESTADO'), ('2', 'DEVUELTO'), ('3', 'ATRASADO')], default='1', max_length=9)),
                ('observaciones_entrega', models.TextField(help_text='El equipo no presenta ningun fallo, rasguño, golpe, etc')),
                ('observaciones_devolucion', models.TextField(blank=True, help_text='El equipo se devuelve sin ninguna falla, rasguño, golpe, etc', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', related_query_name='item', to='inventario.item')),
            ],
        ),
    ]
