# Generated by Django 6.0.3 on 2026-05-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_Categoria',
            new_name='nombre_categoria',
        ),
    ]
