# Generated by Django 6.0.3 on 2026-05-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_rename_nombre_categoria_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', related_query_name='categoria', to='Inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', related_query_name='item', to='Inventario.item'),
        ),
    ]
