# Generated by Django 6.0.3 on 2026-05-28 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0004_datos_demo_contabilidad'),
        ('RecursosHumanos', '0005_datos_demo_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('plataforma_origen', models.CharField(max_length=80)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('fecha_importacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_empleados', models.IntegerField(default=0)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('importado', 'Importado'), ('validado', 'Validado'), ('inconsistencias', 'Con inconsistencias'), ('contabilizado', 'Contabilizado')], default='importado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lote de nomina',
                'verbose_name_plural': 'Lotes de nomina',
                'ordering': ['-anio', '-fecha_importacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='nomina',
            options={'verbose_name': 'Nomina', 'verbose_name_plural': 'Nominas'},
        ),
        migrations.CreateModel(
            name='DetalleNominaImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_nombre', models.CharField(max_length=120)),
                ('empleado_cedula', models.CharField(max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('inconsistencia', 'Inconsistencia')], default='ok', max_length=20)),
                ('mensaje_validacion', models.CharField(blank=True, max_length=250)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nomina', to='RecursosHumanos.empleado')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Contabilidad.lotenomina')),
            ],
            options={
                'verbose_name': 'Detalle de nomina importada',
                'verbose_name_plural': 'Detalles de nomina importada',
                'ordering': ['empleado_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoNominaImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('devengado', 'Devengado'), ('deduccion', 'Deduccion')], max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='Contabilidad.detallenominaimportada')),
            ],
            options={
                'verbose_name': 'Concepto de nomina importada',
                'verbose_name_plural': 'Conceptos de nomina importada',
                'ordering': ['tipo', 'codigo'],
            },
        ),
    ]
