# Generated by Django 6.0.3 on 2026-05-28 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0005_lotenomina_alter_nomina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=150)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Partida presupuestal',
                'verbose_name_plural': 'Partidas presupuestales',
                'ordering': ['area', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='PlanPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.IntegerField(unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('ejecucion', 'En ejecucion'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan presupuestal',
                'verbose_name_plural': 'Planes presupuestales',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='AjustePresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aumento', 'Aumento'), ('reduccion', 'Reduccion'), ('traslado_entrada', 'Traslado de entrada'), ('traslado_salida', 'Traslado de salida')], max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=20)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='Contabilidad.partidapresupuestal')),
            ],
            options={
                'verbose_name': 'Ajuste presupuestal',
                'verbose_name_plural': 'Ajustes presupuestales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='partidapresupuestal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='Contabilidad.planpresupuestal'),
        ),
        migrations.CreateModel(
            name='RevisionPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3'), (4, 'Trimestre 4')])),
                ('fecha_revision', models.DateField(default=django.utils.timezone.now)),
                ('decision', models.CharField(choices=[('mantener', 'Mantener'), ('ajustar', 'Ajustar'), ('congelar', 'Congelar'), ('ampliar', 'Ampliar')], max_length=20)),
                ('observaciones', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='Contabilidad.planpresupuestal')),
            ],
            options={
                'verbose_name': 'Revision presupuestal',
                'verbose_name_plural': 'Revisiones presupuestales',
                'ordering': ['-fecha_revision'],
                'unique_together': {('plan', 'trimestre')},
            },
        ),
    ]
