# Generated by Django 6.0.3 on 2026-03-25 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=20)),
                ('semestre', models.IntegerField()),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField(default=3)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asiste', models.BooleanField(default=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('corte', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del profesor')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.inscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.programa'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.rol')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestionAcademica.usuario'),
        ),
    ]


