# Generated by Django 6.0.3 on 2026-05-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0003_sistema_calificacion_avanzado'),
        ('gestionAcademica', '0006_restaurar_usuarios_demo'),
    ]

    operations = [
    ]
