# Generated by Django 6.0.3 on 2026-05-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0007_merge_20260527_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(help_text='Ej: Quiz 1, Taller Algoritmos, Examen Parcial', max_length=200),
        ),
        migrations.AlterField(
            model_name='calificacionactividad',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del profesor (retroalimentación)'),
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_corte', models.IntegerField(choices=[(1, 'Corte 1'), (2, 'Corte 2'), (3, 'Corte 3')], help_text='Número del corte (1, 2 o 3)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='gestionAcademica.inscripcion')),
            ],
            options={
                'verbose_name_plural': 'Cortes',
                'ordering': ['inscripcion', 'numero_corte'],
                'unique_together': {('inscripcion', 'numero_corte')},
            },
        ),
    ]
