# Generated by Django 6.0.3 on 2026-05-28 19:26

import django.db.models.deletion
import unicodedata
from django.db import migrations, models


TODOS_LOS_MODULOS = ['academica', 'contabilidad', 'rrhh', 'inventario', 'solicitudes']

ROLE_MODULES = {
    'super administrador': TODOS_LOS_MODULOS,
    'administrador general': TODOS_LOS_MODULOS,
    'administrador': TODOS_LOS_MODULOS,
    'admin': TODOS_LOS_MODULOS,
    'coordinador academico': ['academica', 'solicitudes'],
    'profesor': ['academica', 'solicitudes'],
    'estudiante': ['academica', 'solicitudes'],
    'contador': ['contabilidad', 'solicitudes'],
    'contabilidad': ['contabilidad', 'solicitudes'],
    'director financiero': ['contabilidad', 'solicitudes'],
    'auxiliar contable': ['contabilidad', 'solicitudes'],
    'recursos humanos': ['rrhh', 'solicitudes'],
    'rrhh': ['rrhh', 'solicitudes'],
    'director talento humano': ['rrhh', 'solicitudes'],
    'auxiliar talento humano': ['rrhh', 'solicitudes'],
    'inventario': ['inventario', 'solicitudes'],
    'coordinador inventario': ['inventario', 'solicitudes'],
    'auxiliar inventario': ['inventario', 'solicitudes'],
    'solicitudes': ['solicitudes'],
    'gestor solicitudes': ['solicitudes'],
}


def normalizar_rol(nombre):
    texto = str(nombre or '').strip().lower()
    texto = unicodedata.normalize('NFKD', texto)
    return ''.join(caracter for caracter in texto if not unicodedata.combining(caracter))


def modulos_default(nombre_rol):
    rol = normalizar_rol(nombre_rol)
    if rol in ROLE_MODULES:
        return ROLE_MODULES[rol]
    if 'super' in rol or 'admin' in rol or 'rector' in rol:
        return TODOS_LOS_MODULOS
    if 'prof' in rol or 'estudiante' in rol or 'academ' in rol:
        return ['academica', 'solicitudes']
    if 'cont' in rol or 'financ' in rol:
        return ['contabilidad', 'solicitudes']
    if 'humano' in rol or 'talento' in rol or 'rrhh' in rol:
        return ['rrhh', 'solicitudes']
    if 'invent' in rol:
        return ['inventario', 'solicitudes']
    if 'solicitud' in rol:
        return ['solicitudes']
    return ['solicitudes']


def sembrar_permisos_roles(apps, schema_editor):
    Rol = apps.get_model('gestionAcademica', 'Rol')
    PermisoRolModulo = apps.get_model('gestionAcademica', 'PermisoRolModulo')
    for rol in Rol.objects.all():
        permitidos = set(modulos_default(rol.nombre_rol))
        for modulo in TODOS_LOS_MODULOS:
            PermisoRolModulo.objects.get_or_create(
                rol=rol,
                modulo=modulo,
                defaults={'activo': modulo in permitidos},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAcademica', '0009_actividad_numero_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoRolModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('academica', 'Gestion Academica'), ('contabilidad', 'Contabilidad'), ('rrhh', 'Recursos Humanos'), ('inventario', 'inventario'), ('solicitudes', 'Solicitudes')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_modulo', to='gestionAcademica.rol')),
            ],
            options={
                'verbose_name': 'Permiso por rol',
                'verbose_name_plural': 'Permisos por rol',
                'ordering': ['rol__nombre_rol', 'modulo'],
                'unique_together': {('rol', 'modulo')},
            },
        ),
        migrations.RunPython(sembrar_permisos_roles, migrations.RunPython.noop),
    ]
